config/routes.rb
Questionnaire::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :subjects
  resources :mockexams do
    resources :mock_questions do
      resources :mock_answers do
        resources :mock_correct_answers
      end
    end
  end
  resources :surveys
  root to: 'surveys#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
    belongs_to :mock_answer
end

app/models/level.rb
class Level < ApplicationRecord
    has_many :mockexams
    has_many :subjects
end

app/models/mock_answer.rb
class MockAnswer < ApplicationRecord
    belongs_to :mock_question
    has_one :mock_correct_answer
    accepts_nested_attributes_for :mock_correct_answer, allow_destroy: true
end

app/models/mock_correct_answer.rb
class MockCorrectAnswer < ApplicationRecord
    belongs_to :mock_answer
end

app/models/mock_question.rb
class MockQuestion < ApplicationRecord
    belongs_to :mock_exams
    has_many :mock_answers
    accepts_nested_attributes_for :mock_answers, allow_destroy: true
end

app/models/mockexam.rb
class Mockexam < ApplicationRecord
    has_many :mock_questions
    belongs_to :level
    accepts_nested_attributes_for :mock_questions, allow_destroy: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :level
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mockexams_controller.rb
class MockexamsController < ApplicationController
  before_action :set_mockexam, only: [:show, :edit, :update, :destroy]

  # GET /mockexams
  def index
    @mockexams = Mockexam.all
  end

  # GET /mockexams/1
  def show
  end

  # GET /mockexams/new
  def new
    @mockexam = Mockexam.new
  end

  # GET /mockexams/1/edit
  def edit
  end

  # POST /mockexams
  def create
    @mockexam = Mockexam.new(mockexam_params)

    if @mockexam.save
      redirect_to @mockexam, notice: 'Mockexam was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /mockexams/1
  def update
    if @mockexam.update(mockexam_params)
      redirect_to @mockexam, notice: 'Mockexam was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /mockexams/1
  def destroy
    @mockexam.destroy
    redirect_to mockexams_url, notice: 'Mockexam was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mockexam
      @mockexam = Mockexam.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def mockexam_params
      params.require(:mockexam).permit(:name, :level_id, :subject_id, {:mock_questions => [{:mock_answers => [:mock_question_id, :content], :mock_correct_answers => [:content,:mock_answer_id] } ]})
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to @subject, notice: 'Subject was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /subjects/1
  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: 'Subject was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subjects/1
  def destroy
    @subject.destroy
    redirect_to subjects_url, notice: 'Subject was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def subject_params
      params.require(:subject).permit(:name, :level_id)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(params[:survey])
    if @survey.save
      redirect_to @survey, notice: "Successfully created survey."
    else
      render :new
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes(params[:survey])
      redirect_to @survey, notice: "Successfully updated survey."
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_url, notice: "Successfully destroyed survey."
  end

  def survey_params
    params.require(:survey).permit(:name,{:questions => [{:answers => [:question_id, :content] }]})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/mockexams_helper.rb
module MockexamsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaire</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/mockexams/_form.html.erb
<%=  simple_form_for(@mockexam, html: { class: 'form-inline' }) do |f| %>
  <% if mockexam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mockexam.errors.count, "error") %> prohibited this mockexam from being saved:</h2>

      <ul>
      <% mockexam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name, id: :mockexam_name %>
  </div>

  <div class="field">
    <%= f.input :level_id, id: :mockexam_level_id %>
  </div>

  <div class="field">
    <%= f.input :subject_id, id: :mockexam_subject_id %>
  </div>

  <%= f.simple_fields_for :mock_questions do |builder| %>
    <%= render partial: 'mock_question_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Question", f, :mock_questions %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mockexams/_mock_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Question" %><br />
  <%= f.input :content %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <%= f.simple_fields_for :mock_correct_answers do |builder| %>
    <%= render 'mock_correct_answer_fields', f: builder %>
  <% end %>
  
</fieldset>

app/views/mockexams/_mock_correct_answer_fields.html.erb
<fieldset>
  <%= f.input :content %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Answer" %>
</fieldset>

app/views/mockexams/_mock_question_fields.html.erb
<fieldset>
  <%= f.label :content, "Question" %><br />
  <%= f.input :content %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <%= f.simple_fields_for :mock_answers do |builder| %>
    <%= render 'mock_answer_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :mock_answers %>
</fieldset>

app/views/mockexams/edit.html.erb
<h1>Editing Mockexam</h1>

<%= render 'form', mockexam: @mockexam %>

<%= link_to 'Show', @mockexam %> |
<%= link_to 'Back', mockexams_path %>

app/views/mockexams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mockexams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mockexams.each do |mockexam| %>
      <tr>
        <td><%= mockexam.name %></td>
        <td><%= mockexam.level_id %></td>
        <td><%= mockexam.subject_id %></td>
        <td><%= link_to 'Show', mockexam %></td>
        <td><%= link_to 'Edit', edit_mockexam_path(mockexam) %></td>
        <td><%= link_to 'Destroy', mockexam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mockexam', new_mockexam_path %>

app/views/mockexams/new.html.erb
<h1>New Mockexam</h1>

<%= render 'form', mockexam: @mockexam %>

<%= link_to 'Back', mockexams_path %>

app/views/mockexams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mockexam.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @mockexam.level_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @mockexam.subject_id %>
</p>

<%= link_to 'Edit', edit_mockexam_path(@mockexam) %> |
<%= link_to 'Back', mockexams_path %>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="field">
    <%= form.label :level_id %>
    <%= form.number_field :level_id, id: :subject_level_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.level_id %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @subject.level_id %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<%= form_for @survey do |f| %>
  <% if @survey.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Question", f, :questions %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :content %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %>
</fieldset>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render "form" %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<% @surveys.each do |survey| %>
  <div class="article">
    <h2><%= link_to survey.name, survey %></h2>
    <%= pluralize(survey.questions.size, "Question") %>
  </div>
<% end %>

<p><%= link_to 'New Survey', new_survey_path %></p>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "form" %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>

<ol class="questions">
<% @survey.questions.each do |question| %>
  <li>
    <%= question.content %>
    <ol class="answers">
      <% question.answers.each do |answer| %>
        <li><%= answer.content %></li>
      <% end %>
    </ol>
  </li>
<% end %>
</ol>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back to Surveys', surveys_path %>